### ISSUE TITLE
Enhance webrtc NS with rnn?

### ISSUE THREAD

**Issue by jiangjianping** [xiph/rnnoise#143]
The rnn works great with the original pcm input. The webRTC NS not worked very well in some noisy enviroment. I tried to replace the webrtc NS module with rnn after webrtc AEC3, but the voice is corrupt. Is it possible to integrate this with webrtc real communication?

**Comment by brianburt** [comment]
I'm very intrested in this as well. We have a conferencing tool that uses WebRTC front-end (and Janus and/or Freeswitch as the server) and saw from OBS that they say this is working very well.

**Comment by jzi040941** [comment]
RNNoise is already applied to webrtc agc2(auto gain controll) since RNNoise is reducing noise by band gain controll. (But quality of webrtc agc2 is not 100% working as we expected. one reason that I assume is RNNoise is trained 40khz ~ 52kHz samplerate data as you can see on paper not on under 40kHz samplerate data. usually the input of webrtc data is 16kHz)

**Comment by jiangjianping** [comment]
@jzi040941 
Happy new year. Any progress in the he webrtc vad based on rnnoise ?

**Comment by jzi040941** [comment]
@jiangjianping 
Happy new year too!. Do you mean on my github repo? Or in WebRTC VAD?

**Comment by jiangjianping** [comment]
@jzi040941 ,
Where is your github repo?

**Comment by jiangjianping** [comment]
put the rnn after aec, works
